apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kitchen1-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.201-192.168.0.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: kitchen1-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - kitchen1-pool